### ISSUE TITLE
IllegalArgumentException with `:aot :all` and `lein trampoline run` 

### ISSUE THREAD

**Issue by DrTom** [weavejester/clout#27]
I get the following error when setting `:aot :all` and starting the application with `lein trampoline run`: 

```
java.lang.IllegalArgumentException: No implementation of method: :route-matches of protocol: #'clout.core/Route found for class: clout.core.CompiledRoute
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554)
        at clout.core$fn__3514$G__3509__3521.invoke(core.clj:39)
        at compojure.core$if_route$fn__3677.invoke(core.clj:40)
```

I can reproduce this problem if and only if the two conditions mentioned above are in place. So it is not hard to find a workaround but a fix would be appreciated (I did cost me about 2 hours to figure it out). 

There seem to be other ways to get the same problem and it might help to see the underlying problem: 
1. http://stackoverflow.com/questions/31129470/java-lang-illegalargumentexception-no-implementation-of-method-route-matches
2. http://stackoverflow.com/questions/18542956/can-anybody-explain-why-compojures-routing-macro-only-accepts-literal-vector-as

**Comment by weavejester** [comment]
Errors of this type tend to be caused by outdated class files on the classpath. Sometimes you can solve it by cleaning the target directory, but sometimes it's caused by classfiles included in a dependency or plugin you're using.

This probably isn't going to be something I can fix in Clout, because the likelihood is that this is being caused by another dependency. You can try a `lein clean` and see if the problem persists, and if it does try posting your dependencies and plugins (including those in `~/.lein/profiles.clj`).

**Comment by otwieracz** [comment]
So right now I've got similar problem when trying to start uberjar. And I see no workaround for my case:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.lang.Namespace.<init>(Namespace.java:34)
        at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
        at clojure.lang.Var.internPrivate(Var.java:153)
        at mysoftwared.core.<clinit>(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: clout/core/CompiledRoute, compiling:(user.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.RT.loadResourceScript(RT.java:379)
        at clojure.lang.RT.loadResourceScript(RT.java:366)
        at clojure.lang.RT.maybeLoadResourceScript(RT.java:362)
        at clojure.lang.RT.doInit(RT.java:482)
        at clojure.lang.RT.<clinit>(RT.java:336)
        ... 4 more
Caused by: java.lang.NoClassDefFoundError: clout/core/CompiledRoute
        at mysoftwared.api__init.__init0(Unknown Source)
        at mysoftwared.api__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2204)
        at clojure.lang.RT.classForName(RT.java:2213)
        at clojure.lang.RT.loadClassForName(RT.java:2232)
        at clojure.lang.RT.load(RT.java:450)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
```

My list of dependencies, if this helps in any way:
```
  :dependencies [[clj-systemd "0.1.0-SNAPSHOT"]
                 [com.cognitect/transit-clj "0.8.309"]
                 [compojure "1.6.1"]
                 [io.clojure/liberator-transit "0.3.1"]
                 [environ "1.1.0"]
                 [expound "0.7.1"]
                 [liberator "0.15.1"]
                 [me.raynes/fs "1.4.6"]
                 [org.clojure/clojure "1.9.0"]
                 [org.clojure/test.check "0.9.0"]
                 [org.clojure/tools.cli "0.3.7"]
                 [org.clojure/tools.logging "0.4.1"]
                 [org.danielsz/system "0.4.1"]
                 [ring/ring-core "1.6.3"]
                 [ring/ring-jetty-adapter "1.6.3"]]
```

**Comment by weavejester** [comment]
Have you tried performing a `lein clean`? Are you AOTing Clout? Do you have any AOTed libraries in your dependencies, or in your plugin dependencies?

**Comment by otwieracz** [comment]
Yes, I've tried `lein clean` and as far as I know I am AOTing `:all`. See here: https://clojureverse.org/t/noclassdeffounderror-clout-core-compiledroute-with-compjure-liberator-and-ring-possibly/2682

**Comment by weavejester** [comment]
It looks like you're skipping a namespace in your project file, so you could try removing that. You also haven't said whether you've checked all dependencies and all dependencies pulled in via a plugin for compiled class files.

My advice would be to remove your `target` directory, remove any Leiningen plugins you are using (project specific *and* global), and make sure all your dependencies are up to date. Check `lein deps :tree` for dependency conflicts and resolve them. If it still fails check the jars in the `.m2` directory for accidentally class files. 

This is general advice and not specific to Clout. Since this issue seems to be an issue with Clojure rather than Clout itself, I'm closing this issue (though you may continue to reply).
